version: '3'
services:
  api:
    build: .
    ports:
       - 5000:5000
    command: python svc/app/api.py
  celery:
    build: .
    command: celery -A svc.tasks.tasks worker -Q <queue name> -l info --concurrency=1 -E --time-limit=10

